"""empty message

Revision ID: 17651f477a37
Revises: d3054ddc4d66
Create Date: 2023-08-28 10:14:33.059121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17651f477a37'
down_revision = 'd3054ddc4d66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=300), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
