"""empty message

Revision ID: 3937db90f4a8
Revises: 17651f477a37
Create Date: 2023-09-02 17:51:32.544455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3937db90f4a8'
down_revision = '17651f477a37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tagged_recommendations', schema=None) as batch_op:
        batch_op.drop_constraint('tagged_recommendations_recommendation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recommendation', ['recommendation_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tagged_recommendations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tagged_recommendations_recommendation_id_fkey', 'recommendation', ['recommendation_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
